### ISSUE TITLE
failed！

### ISSUE THREAD

**Issue by MrShuimitao** [NoWhereMan1979/VMWare-BigSur#1]
hello！noWhereman, I failed. The installation stops on the startup screen
![(YGM7${P`O~@$FTOH2QCC7X](https://user-images.githubusercontent.com/28756145/122680097-41396900-d220-11eb-95af-cc5d93050e36.png)
 VMware version is 16.1.2!
Help me!

**Comment by NoWhereMan1979** [comment]
Hi, is there any detail or error?
Have you unlocked the VMWare using vmware unlocker? I mean, when you make a new vm, is there any macOS to select as guest OS?

**Comment by MrShuimitao** [comment]
I have unlocked the VMware

**Comment by NoWhereMan1979** [comment]
Actually this machine was built in an earlier version of vmware that i dont remember which one was it. maybe 15 it was. After fails in new vmware versions, just tested this old vmx to make a machine and suddenly installation succeeded. I didn't do any trick on this file.

**Comment by MrShuimitao** [comment]
Emmmm. So I bought a macbook. 🤣

**Comment by MrShuimitao** [comment]
thank u
